apiVersion: v1
kind: Secret
metadata:
    name: github-repo-secret
    labels:
        argocd.argoproj.io/secret-type: repo-creds
stringData:
    type: git
    url: git@github.com:flynnt-io
    sshPrivateKey: |-
        -----BEGIN OPENSSH PRIVATE KEY-----
        samplesshkey1
        samplesshkey2
        samplesshkey3
        samplesshkey4
        samplesshkey5
        -----END OPENSSH PRIVATE KEY-----
