apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - https://github.com/argoproj/argo-cd/manifests/crds?ref=v2.8.4
  - https://github.com/argoproj/argo-cd/manifests/namespace-install?ref=v2.8.4
  - base/ingress.yaml

patches:
  - path: overlays/argocd-cm.yaml
  - path: overlays/argocd-rbac-cm.yaml
  - path: overlays/argocd-repo-server.yaml

generators:
  - ./secret-generator.yaml
